version: '3'
  
services:

  mysql_db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - /var/data/mysql-data:/var/lib/mysql
    ports:
      - "9906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE

  apigateway:
    image: apigateway:5
    depends_on:
      - usermanagement
      - userinterface
      - enquiryprocess
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./apigateway
    ports:
      - "80:80"

  usermanagement:
    image: usermanagement:2
    build:
      dockerfile: Dockerfile
      context: "./usermanagement"
    depends_on:
      - mysql_db
    environment:
      DB_HOSTNAME: mysql_db
    ports:
      - "3002:3002"
  
  enquiryprocess:
    image: enquiryprocess:2
    build:
      dockerfile: Dockerfile
      context: "./enquiryprocess"
    depends_on:
      - mysql_db
    environment:
      DB_HOSTNAME: mysql_db
    ports:
      - "3001:3001"

  userinterface: 
    image: userinterface:2
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: 
      dockerfile: Dockerfile
      context: ./userinterface

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db